data_pipelines_v2_1:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: VS@123
      port: 5432
      dbname: She_for_STEM_V2 # or database instead of dbname
      schema: staging
      threads: 4