version: 2
sources:
  - name: raw
    schema: raw  # The schema where your raw data tables are stored
    tables:
      # @@TO-DO: specifify all the raw table names and schemas after loading those 15+ csv files
      - name: general_information_sheet
        description: "Raw student registration data from CSV file"    
      - name: payment_details
        description: "Raw payment details data from CSV file"
      - name: enroll_date
        description: "Raw student enroll date data from CSV file"
      - name: student_progress
        description: "Raw student progress data from CSV file"
      - name: overall_attendance_summary
        description: "Raw student overall attendance data from CSV file"
      - name: performance_monitoring_summary
        description: "Raw student performance monitoring data from CSV file"
      - name: summary_overall_performance_monitoring
        description: "Raw student overall performance monitoring data from CSV file"
      - name: incubator_and_attendance_monitoring
        description: "Raw student incubator and attendance data from CSV file"
      - name: weekly_attendence
        description: "Raw student weekly attendance data from CSV file"
      - name: incubator_quiz_monitoring
        description: "Raw student incubator quiz monitoring data from CSV file"
      - name: incubator_assignment_monitoring
        description: "Raw student incubator assignment monitoring data from CSV file"
      - name: track_attendance_monitoring
        description: "Raw student attendance monitoring data from CSV file"
      - name: live_tracks_attendance_monitoring
        description: "Raw student live attendance monitoring data from CSV file"
      - name: internship_attendence_monitoring
        description: "Raw student internship attendance monitoring data from CSV file"
      - name: batch_lastlogin_startdate
      - name: college_wise_leaderboard
      - name: accelerator_mentor_interaction_attendance
      - name: accelerator_project_performance_tracking
        description: "Raw student accelerator project performance tracking data from CSV file"
      - name: accelerator_and_attendance_monitoring
        description: "Raw student accelerator and attendance monitoring data from CSV file"
      - name: accelerator_overall_attendance_tracking
        description: "Raw student accelerator overall attendance tracking data from CSV file"
      - name: timestamp_videos
      - name: cohort_wise_notation
      - name: mentor_recruitment
        description: "Raw mentor details data"
      - name: cohort_details
        description: "Raw cohort details data"
      - name: session_details
        description: "Raw session_details data"
      - name: student_session_information
        description: "Raw student attended session details data"
      - name: resource_details
        description: "Raw resource shared like pre-recorded videos, assignments,.. details"
      - name: general_information_sheet_f