
version: 2

models:
  - name: student
    description: "Student registration details"
    columns:
      - name: id
        constraints:
          - type: not_null
          - type: primary_key
      - name: email
        data_type: text
      - name: first_name
        data_type: text
      - name: last_name
        data_type: text
      - name: country # need to be changed to country_code once seeds are in place
        data_type: text
      - name: gender
        data_type: varchar(1)
        description: F/M/O
      - name: phone   # need to be validated and cleaned for [optional country code] and 10 digit number
        data_type: text
      - name: date_of_birth
        data_type: date
      - name: caste
        data_type: text
      - name: annual_family_income
        data_type: text
      # - name: created_at
      #   data_type: timestamp
      # - name: updated_at
      #   data_type: timestamp
