
version: 2

models:
  - name: student
    description: "Stores basic student information"
    columns:
      - name: id
        constraints:
          - type: not_null
          - type: primary_key
      - name: email
        data_type: text
      - name: first_name
        data_type: text
      - name: last_name
        data_type: text
      - name: country # need to be changed to country_code once seeds are in place
        data_type: text
      - name: gender
        data_type: varchar(1)
        description: F/M/O
      - name: phone   # need to be validated and cleaned for [optional country code] and 10 digit number
        data_type: text
      - name: date_of_birth
        data_type: date
      - name: caste
        data_type: text
      - name: annual_family_income
        data_type: text
      - name: id  #primary key in location table
        description: "References the student location from location table"
        tests:
          - not_null
          - relationships:
              to: ref('location')
              field: location_id
      # - name: created_at
      #   data_type: timestamp
      # - name: updated_at
      #   data_type: timestamp

  - name: location
    description: "Student location details"
    columns:
      - name: id
        constraints:
          - type: not_null
          - type: primary_key
      - name: country
        data_type: text
      - name: state_union_territory
        data_type: text
      - name: district
        data_type: text
      - name: location_category 
        data_type: text

  - name: registration_details
    description: "Stores student registration details and application reasons"
    columns:
      - name: id
        constraints:
          - type: not_null
          - type: primary_key
      - name: id #primary key in student table
        description: "References the student from student table"
        tests:
          - not_null
          - relationships:
              to: ref('student')
              field: student_id
      - name: assigned_through
        data_type: text
      - name: how_did_you_hear_about_us
        data_type: text
      - name: registration_date
        data_type: date
      - name: is_studying_STEM_fields 
        data_type: boolean
      - name: reason_for_applying 
        data_type: text
      - name: problems_faced_in_studies_and_career
        data_type: text
      
      