
version: 2

models:
  - name: student
    description: "Stores basic student information"
    columns:
      - name: id
        constraints:
          - type: not_null
          - type: primary_key
      - name: email
        data_type: text
      - name: first_name
        data_type: text
      - name: last_name
        data_type: text
      - name: country # need to be changed to country_code once seeds are in place
        data_type: text
      - name: gender
        data_type: varchar(1)
        description: F/M/O
      - name: phone   # need to be validated and cleaned for [optional country code] and 10 digit number
        data_type: text
      - name: date_of_birth
        data_type: date
      - name: caste
        data_type: text
      - name: annual_family_income
        data_type: text
      - name: location_id  #primary key in location table
        description: "References the student location from location table"
        tests:
          - not_null
          - relationships:
              to: ref('location')
              field: location_id
      # - name: created_at
      #   data_type: timestamp
      # - name: updated_at
      #   data_type: timestamp

  - name: location
    description: "Student location details"
    columns:
      - name: id
        constraints:
          - type: not_null
          - type: primary_key
      - name: country
        data_type: text
      - name: state_union_territory
        data_type: text
      - name: district
        data_type: text
      - name: location_category 
        data_type: text

  - name: student_registration_details
    description: "Stores student registration details and application reasons"
    columns:
      - name: id
        constraints:
          - type: not_null
          - type: primary_key
      - name: student_id #primary key in student table
        description: "References the student from student table"
        tests:
          - not_null
          - relationships:
              to: ref('student')
              field: student_id
      - name: assigned_through
        data_type: text
      - name: how_did_you_hear_about_us
        data_type: text
      - name: registration_date
        data_type: date
      - name: is_studying_STEM_fields 
        data_type: boolean
      - name: reason_for_applying 
        data_type: text
      - name: problems_faced_in_studies_and_career
        data_type: text

  - name: subject
    description: "Stores students subject details"
    columns:
      - name: id
        description: "Primary key for the subject table"
        tests:
          - not_null
          - primary_key

      - name: subject_name
        description: "Name of the subject"
        data_type: text

      - name: display_name
        description: "Display name of the subject"
        data_type: text


  - name: education_category
    description: "Education category details"
    columns:
      - name: id
        description: "Primary key for the eduaction category table"
        tests:
          - not_null
          - primary_key

      - name: category_name
        description: "Name of the category"
        data_type: text
  
  - name: education_course
    description: "Education details"
    columns:
      - name: id
        description: "Primary key for the education course table"
        tests:
          - not_null
          - primary_key

      - name: course_name
        description: "Name of the course"
        data_type: text

      - name: display_name
        description: "Display name"

  - name: college
    description: "college details"
    columns:
      - name: id
        description: "Primary key for the college table"
        tests:
          - not_null
          - primary_key
      
      - name: id  #primary key in location table
        description: "References the location from location table"
        tests:
          - not_null
          - relationships:
              to: ref('location')
              
      - name: university
        description: "Name of the university"
        data_type: text

      - name: college
        description: "college name"

  - name: student_documents
    description: "student document details"
    columns:
      - name: id
        description: "Primary key for the college table"
        tests:
          - not_null
          - primary_key
      
      - name: student_id  #primary key in student table
        description: "References the student from student table"
        tests:
          - not_null
          - relationships:
              to: ref('student')
              
      - name: document_name
        description: "Name of the document"
        data_type: text

      - name: document
        description: "Uploaded document"
        data_type: BYTEA

  - name: programs
    description: "Table containing program details including their codes, names, and start dates."
    columns:
      - name: program_code
        description: "Short code identifier for the program (e.g., INC, ACC, STC)."
        data_type: varchar(10)
        tests:
          - not_null
          - unique

      - name: program_name
        description: "Full name of the program (e.g., Incubation Program, Accelerator Program, STEM Champions)."
        data_type: varchar(100)

      - name: start_date
        description: "Start date of the program."
        data_type: date    

  - name: mentor_details
    description: "Table containing mentor details"
    columns:
      - name: id
        description: "Primary key for the college table"
        tests:
          - not_null
          - primary_key
      - name: mentor_name
        description: "Name of the mentor"
        data_type: varchar(50)
      - name: email_id
        description: "Email_id of the mentor"
        data_type: varchar(50)
      - name: linkedIn_url
        description: "LinkedIn url of the mentor"
        data_type: text
      - name: current_position
        description: "Current position"
        data_type: varchar(100)
      - name: phone_number
        description: "Phone number"
        data_type: varchar
      - name: joined_on
        description: "Date of joining"
        data_type: date
      - name: is_active
        description: "Is mentor active in the cohort"
        data_type: boolean

  - name: cohort
    description: "Table containing cohort details"
    columns:
      - name: cohort_code
        description: "Primary key for the cohort table"
        tests:
          - not_null
          - primary_key
      - name: program_code
        description: "References the Program code - INC,ACC,STC"
        tests:
          - not_null
          - relationships:
              to: ref('programs')
              field: program_code
        data_type: varchar(50)
      - name: cohort_number
        description: "Cohort number"
        data_type: varchar(50)
      - name: cohort_name
        description: "Cohort name"
        data_type: varchar(50)
      - name: type
        description: "Type of cohort"   -- open, curriculum
        data_type: enum
      - name: start_date
        description: "Start date of cohort"
        data_type: date
      - name: end_date
        description: "End date of cohort"
        data_type: date
      - name: is_active
        description: "Is the cohort active or not"
        data_type: boolean


  - name: student_cohort
    description: "Table containing students cohort details"
    columns:
      - name: student_code
        description: "Primary key for the student cohort table"
        tests:
          - not_null
          - primary_key   
      - name: student_id
        description: "References the student ids from student table"
        tests:
          - not_null
          - relationships:
              to: ref('student')
              field: student_id
      - name: cohort_code
        description: "References the cohort codes from cohort table"
        tests:
          - not_null
          - relationships:
              to: ref('cohort')
              field: cohort_code
      - name: is_leader
        description: "Is student leader or not"
        data_type: varchar(50)
      - name: cohort_enroll_date
        description: "Student enroll date in cohort"
        data_type: date
      